# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.26)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS libhighs libipx libbasiclu)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target libhighs
add_library(libhighs SHARED IMPORTED)

set_target_properties(libhighs PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include"
  INTERFACE_LINK_LIBRARIES "libipx;/Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/lib/libz.tbd;Threads::Threads"
)

# Create imported target libipx
add_library(libipx SHARED IMPORTED)

set_target_properties(libipx PROPERTIES
  INTERFACE_LINK_LIBRARIES "libbasiclu"
)

# Create imported target libbasiclu
add_library(libbasiclu SHARED IMPORTED)

# Import target "libhighs" for configuration "Debug"
set_property(TARGET libhighs APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(libhighs PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/ethandeakins/Work/OC/EQLPSolver/HiGHS-1-2-1/build_debug/lib/libhighs.1.2.1.dylib"
  IMPORTED_SONAME_DEBUG "/Users/ethandeakins/Work/OC/EQLPSolver/HiGHS-1-2-1/build_debug/lib/libhighs.1.2.dylib"
  )

# Import target "libipx" for configuration "Debug"
set_property(TARGET libipx APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(libipx PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/ethandeakins/Work/OC/EQLPSolver/HiGHS-1-2-1/build_debug/lib/libipx.dylib"
  IMPORTED_SONAME_DEBUG "/Users/ethandeakins/Work/OC/EQLPSolver/HiGHS-1-2-1/build_debug/lib/libipx.dylib"
  )

# Import target "libbasiclu" for configuration "Debug"
set_property(TARGET libbasiclu APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(libbasiclu PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/ethandeakins/Work/OC/EQLPSolver/HiGHS-1-2-1/build_debug/lib/libbasiclu.dylib"
  IMPORTED_SONAME_DEBUG "/Users/ethandeakins/Work/OC/EQLPSolver/HiGHS-1-2-1/build_debug/lib/libbasiclu.dylib"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
